#!/bin/bash

# After entering arch-chroot

pacman -S grub efibootmgr networkmanager network-manager-applet dialog wpa_supplicant mtools dosfstools base-devel linux-lts-headers avahi \
  bash-completion openssh os-prober man-db unrar p7zip sed awk intel-ucode


systemctl enable NetworkManager
systemctl enable avahi-daemon
systemctl enable bluetooth
systemctl enable cups.service
systemctl enable sshd
systemctl enable systemd-timesyncd
